name: Auto Check-In

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: ${{ secrets.COOKIE }}
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: workflows/yarn.lock
          
      - name: Debug info
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing files:"
          ls -la
          echo "Listing workflows directory:"
          ls -la workflows/
          
      - name: Install dependencies
        run: cd workflows && yarn install --frozen-lockfile
        
      - name: Run check-in with retry
        run: |
          cd workflows
          for attempt in {1..3}; do
            echo "Attempt $attempt of 3"
            if yarn checkin; then
              echo "Check-in successful on attempt $attempt"
              exit 0
            else
              echo "Check-in failed on attempt $attempt"
              if [ $attempt -lt 3 ]; then
                echo "Waiting 30 minutes before next attempt..."
                sleep 1800
              fi
            fi
          done
          echo "All check-in attempts failed"
          exit 1
